image: louisaldous/cyber-attack-tool-chain:latest

variables:
  MULVALROOT: "/mulval"

stages: 
    - compile

mulvalCompile:
    stage: compile
    script:
        - export
        - cd mulval/
        - mvn install
        - export PATH="$MULVALROOT/bin:$MULVALROOT/utils:$PATH"

clientCompile:
    stage: compile
    script:
        - cd KotlinClient
        - mvn install
    artifacts:
        paths:
            - /mulval
            - /kotlinClient
